Config = {}


Config.vorp = true
Config.redem = false

Config.onesync = true -- new line
Config.bucketblock = 500-- new line

----------------------------------
-- THIS IS ONLY FOR REDEM USERS -- 
Config.HorseLocker = true -- If this is true, horses inventories will be enabled
Config.WagonLocker = true -- If this is true, wagon inventories will be enabled

----------------------------------
Config.searchhorses = true 
Config.searchwagons = true 
Config.policeonly = false
Config.searchjobs = {"police"}

--------------------------------------
Config.callnearstable = false -- turn to true to allow horse calling only near stable 
Config.calldistance = 50 -- how far from stable coords does calling the horse stop

--------------------------------------------------------------
Config.dontallowwagonintown = false 
Config.dontallowhorseintown = false 
Config.BannedTowns = {'Annesburg', 'Armadillo', 'Blackwater', 'Rhodes', 'Siska', 'StDenis', 'Strawberry', 'Tumbleweed', 'Valentine', 'Vanhorn'}

--------------------------------------------------------------
Config.gumfarming = true -- toggle to true if using gum farming
Config.syn_outfitter = true
Config.joblock = false -- turn to true if you want to lock the buy functions to people with a job only 
Config.EnableBuyJobs = {'horsetrainer','government'} -- jobs that can buy
Config.horsedistancecall = 200 -- distance where if the horse is further it will despawn and a new horse will go to player 

Config.supporterselection = false -- supporter only horses, use only if vorp
Config.joblock2 = true -- job lock specific horses can be used for both vorp and redem 

-- only use ints, whole numbers no 1.5 or 0.5 
Config.trainermult = 3 -- any exp generated by a trainer is doubled to decrease reduce the multiplyer to 1
Config.othermult = 1 -- multiply the training points by 1 for non trainers


Config.commands = { -- only change the hashes
["horserest"] = "horserest", --U
["horsewallow"] = "horsewallow", --J
["horsesleep"] = "horsesleep", --H
["horsedrink"] = "horsedrink", --ALT Rear up
}

Config.horsesellrate = 0.5
Config.wagonsellrate = 0.75

Config.keys = { -- only change the hashes
["one"] = 0xD8F73058, --U
["two"] = 0xF3830D8E, --J
["three"] = 0x24978A28, --H
["four"] = 0x8AAA0AD4, --ALT Rear up
["five"] = 0xD9D0E1C0, --space Rear up
["six"] = 0xCEFD9220, -- E -- 

}
Config.horsehealcost = 150 -- cost to heal horse after its dead 
Config.deadtimer = 150000 -- time until horse can be called again, set to 2.5 minutes 
Config.traineronly = false -- only trainers can increase exp
Config.horselead = 40000 -- every 20 seconds increase by 1 bonding for leading
Config.horseride = 40000 -- every 40 seconds increase by 1 bonding for riding
Config.spawnrange = 20.0 ---- make sure the number has .0 in the end, for example 10.0 or 5.0(spawn horse in direction player is facing this amount of units away)
Config.spawnrangewagon = 15.0 ---- make sure the number has .0 in the end, for example 10.0 or 5.0(spawn horse in direction player is facing this amount of units away)
Config.stablelimit = 5 -- normal player stable limit 
Config.stablelimittrainer = 50 -- player with the horse trainer job limit
Config.horsetrainer = {"horsetrainer", "horsetamer"} -- name of horse trainer job given to people in db
Config.wagonlimit = 5 -- limit for wagon stable slots
Config.Stables = { -- very tricky to add more. spawnpoint 1 is for horses 2 is for wagons

	Valentine = {	   
		Pos = {x=-367.73, y=787.72, z=116.26},
		showBlip = true,
		Name = 'Stable',
        Heading = -30.65,
		SpawnPoint = {
			Pos = {x=-387.40, y=780.68, z=115.63},
			CamPos = {x=1, y=-3, z=0},
			Heading = 182.3
		},
		SpawnPoint2 = {
			Pos = {x=-387.40, y=780.68, z=115.63},
			CamPos = {x=1, y=-3, z=0},
			Heading = 336.88
        }
	},

	Blackwater = {
		Pos = {x=-873.167, y=-1366.040, z=43.531},
		showBlip = true,
        Name = 'Stable',
        Heading = 266.84,
        SpawnPoint = {
            Pos = {x=-881.32, y=-1382.7, z=43.8},
            CamPos = {x=-4, y=-5, z=3},
            Heading = 181.91
        },
        SpawnPoint2 = {
            Pos = {x=-881.32, y=-1382.7, z=43.0},
            CamPos = {x=-5, y=-5, z=3},
            Heading = 336.88
        },
	},	

	McLeodTraders = {
		Pos = {x=-1603.56, y=-1411.92, z=81.95},
		showBlip = true,
        Name = 'Stable',
        Heading = 245.0,
        SpawnPoint = {
            Pos = {x=-1585.52, y=-1428.19, z=81.32},
            CamPos = {x=-4, y=-2, z=2},
            Heading = 241.54
        },
        SpawnPoint2 = {
            Pos = {x=-1585.52, y=-1428.19, z=81.32},
            CamPos = {x=-6, y=1, z=2},
            Heading = 241.54
        }		
    },

    SaintDenis = {
		Pos = {x=2503.153, y=-1442.725, z=46.312},
		showBlip = true,
        Name = 'Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=2501.09, y=-1430.4, z=46.0},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 7.2
        },
        SpawnPoint2 = {
            Pos = {x=2501.09, y=-1430.4, z=45.6},
            CamPos = {x=-10, y=10, z=0},
            Heading = 7.2
        }
    },

	BigValley = {
		Pos = {x=-2554.15, y=399.35, z=148.15},
		showBlip = true,
        Name = 'Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=-2544.479, y=419.109, z=148.318},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 357.005
        },
        SpawnPoint2 = {
            Pos = {x=-2540.230, y=418.377, z=148.215},
            CamPos = {x=-5, y=5, z=0},
            Heading = 357.005
        }
    },

--[[ 	Rhodes = {
		Pos = {x=1432.61, y=-1294.74, z=77.82},
		showBlip = true,
        Name = 'Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=1424.25, y=-1311.74, z=77.60},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 94.64
        },
        SpawnPoint2 = {
            Pos = {x=1419.60, y=-1312.26, z=77.62},
            CamPos = {x=-5, y=5, z=0},
            Heading = 285.805
        }
    }, ]]

	macfarlanes = {
		Pos = {x=-2418.36, y=-2392.81, z=61.17},
		showBlip = true,
        Name = 'Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=-2426.88, y=-2371.21, z=61.17},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 94.64
        },
        SpawnPoint2 = {
            Pos = {x=-2430.51, y=-2367.38, z=61.17},
            CamPos = {x=-5, y=5, z=0},
            Heading = 285.805
        }
    },

	tumbleweed = {
		Pos = {x=-5521.27, y=-3044.57, z=-2.38},
		showBlip = true,
        Name = 'Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=-5500.55, y=-3032.37, z=-3.95},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 269.16
        },
        SpawnPoint2 = {
            Pos = {x=-5500.55, y=-3032.37, z=-3.95},
            CamPos = {x=-5, y=5, z=0},
            Heading = 102.71
        }
    },

	rathskellerstable = {
		Pos = {x=-5204.63, y=-2149.50, z=12.12},
		showBlip = true,
        Name = 'Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=-5217.36, y=-2132.40, z=12.09},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 269.16
        },
        SpawnPoint2 = {
            Pos = {x=-5217.36, y=-2132.40, z=12.09},
            CamPos = {x=-5, y=5, z=0},
            Heading = 102.71
        }
    },

--[[ 	armadillo = {
		Pos = {x=-3701.50, y=-2571.08, z=-13.71},
		showBlip = true,
        Name = 'Stables',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=-3699.71, y=-2535.05, z=-13.97},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 323.16
        },
        SpawnPoint2 = {
            Pos = {x=-3700.82, y=-2527.46, z=-13.96},
            CamPos = {x=-5, y=5, z=0},
            Heading = 180.01
        }
    }, ]]

	strawberry = {
		Pos = {x=-1813.69, y=-563.77, z=156.08},
		showBlip = true,
        Name = 'Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=-1795.38, y=-566.26, z=156.08},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 323.16
        },
        SpawnPoint2 = {
            Pos = {x=-1795.38, y=-566.26, z=156.08},
            CamPos = {x=-5, y=5, z=0},
            Heading = 180.01
        }
    },
	vanhorn = {
		Pos = {x=2970.55, y=796.35, z=51.40},
		showBlip = true,
        Name = 'Stable',
        Heading = 169.45,
        SpawnPoint = {
            Pos = {x=2973.69, y=781.05, z=51.23},
            CamPos = {x=-1.8, y=3, z=10},
            Heading = 323.16
        },
        SpawnPoint2 = {
            Pos = {x=2970.57, y=780.05, z=51.39},
            CamPos = {x=-5, y=5, z=0},
            Heading = 180.01
        }
    },

	NearRhodes = {	   
		Pos = {x=1208.37, y=-190.06, z=101.37},
		showBlip = true,
		Name = 'Stable',
        Heading = 198.0,
		SpawnPoint = {
			Pos = {x=1210.74, y=-214.99, z=100.28},
			CamPos = {x=-3.5, y=2.0, z=0},
			Heading = 93.0
		},
		SpawnPoint2 = {
			Pos = {x=1210.74, y=-214.99, z=100.28},
			CamPos = {x=-8.5, y=6.0, z=0.0},
			Heading = 93.0
        }
	}, 


--[[  	EmeraldRanch = {	   
		Pos = {x= 1384.24, y=352.22, z=87.58},
		showBlip = true,
		Name = 'Stable',
        Heading = -30.65,
		SpawnPoint = {
			Pos = {x=1391.22, y=336.48, z=87.60},
			CamPos = {x=1, y=-3, z=0},
			Heading = 182.3
		},
		SpawnPoint2 = {
			Pos = {x=1389.41, y=335.78, z=87.57},
			CamPos = {x=1, y=-3, z=0},
			Heading = 336.88
        }
	},  ]]

	guarma = {	   
		Pos = {x= 1499.68, y=-7069.98, z=76.87},
		showBlip = true,
		Name = 'Stable',
        Heading = 167.05,
		SpawnPoint = {
			Pos = {x=1485.67, y=-7084.22, z=75.14},
			CamPos = {x=-2, y=4, z=0},
			Heading = 31.03
		},
		SpawnPoint2 = {
			Pos = {x=1485.67, y=-7084.22, z=75.14},
			CamPos = {x=-6, y=11, z=0},
			Heading = 31.03
        }
	},

	coulter = {	   
		Pos = {x= -1335.81, y=2398.15, z=307.10},
		showBlip = true,
		Name = 'Stable',
        Heading = -30.65,
		SpawnPoint = {
			Pos = {x=-1314.85, y=2403.85, z=306.86},
			CamPos = {x=1, y=-3, z=0},
			Heading = 182.3
		},
		SpawnPoint2 = {
			Pos = {x=-1314.52, y=2403.55, z=306.90},
			CamPos = {x=1, y=-3, z=0},
			Heading = 336.88
        }
	},
}

	
Config.wagons = { 
	{
		name = "Buggies",
		["cart02"] = {"Buggy 1", 0, 1500, 30,0,{"nojob"}},  ----name WAGON, gold , cash, inventory max items, supporter, job. if cash or gold set to 0 it wont show an option to pay. 
		["buggy01"] = {"Buggy 2", 0, 3500, 30,0,{"nojob"}},  
		["buggy02"] = {"Buggy 3", 0, 5000, 50,0,{"nojob"}},
		["buggy03"] = {"Buggy 4", 0, 6000, 80,0,{"nojob"}},   

	},
	{
		name= "Carts",
		["cart01"] = {"Rustic Cart", 0, 1500, 30,0,{"nojob"}},
		["cart03"] = {"Small Cart 1", 0, 2750, 50,0,{"nojob"}},
		["cart07"] = {"Small Cart 2", 0, 2750, 50,0,{"nojob"}},
		["cart08"] = {"Small Cart 3", 0, 2750, 50,0,{"nojob"}},
		["cart04"] = {"Medium Cart", 0, 3500, 80,0,{"nojob"}},
		["cart06"] = {"Flatbed Cart", 0, 4500, 120,0,{"nojob"}},
		["wagon06x"] = {"Stock Cart", 0, 5000, 120,0,{"nojob"}},
	},
	{
		name = "Coaches",
		["coach6"] = {"Open-Top Coach", 0, 2000, 30,0,{"stagecoach","government"}},
		["coach4"] = {"2-Seater Coach", 0, 2750, 50,0,{"stagecoach","government"}},
		["coach5"] = {"4-Seater Coach", 0, 4000, 80,0,{"horsetrainer","government"}},
		["coach3"] = {"6-Seater Coach", 0, 6000, 80,0,{"horsetrainer","government"}},
	},
	{
		name = "PoliceWagons",
		-- ["gatchuck_2"] = {"Police Gatling 1", 0, 10000, 100,0,{"police","government"}}, 
		-- ["policeWagongatling01x"] = {"Police Gatling 2", 0, 10000, 100,0,{"police","government"}}, 
		-- ["gatchuck"] = {"Gat Chuck 3", 0, 3000, 100,0,{"government","government"}},
		-- ["warwagon2"] = {"War Wagon", 0, 20000, 100,0,{"government"}}, 
		["ArmySupplyWagon"] = {"Army Supply Wagon", 0, 4000, 300,0,{"police","government"}}, 
		["wagonarmoured01x"] = {"Armored Wagon", 0, 5000, 30,0,{"police","government"}},
		["wagonPrison01x"] = {"Prison Wagon", 0, 2500, 30,0,{"police","government"}},
		["bountywagon01x"] = {"Bounty Wagon", 0, 5000, 80,0,{"police","government"}},
	},
	{
		name = "StageCoaches",
		["stagecoach003x"] = {"Open Air Stagecoach", 0, 3000, 80,0,{"stagecoach","government"}},
		["stagecoach006x"] = {"Large 2-Horse Stagecoach", 0, 6000, 300,0,{"horsetrainer","government"}},
		-- ["stagecoach001x"] = {"Small 2-Horse Stagecoach", 0, 3500, 120,0,{"stagecoach","government"}},
		["coach2"] = {"Small 4-Horse Stagecoach", 0, 5000, 120,0,{"stagecoach","government"}},
		["stagecoach002x"] = {"Small 2-Horse Stagecoach", 0, 3000, 120,0,{"stagecoach","government"}},
		["stagecoach005x"] = {"Medium 2-Horse Stagecoach", 0, 4500, 120,0,{"stagecoach","government"}},
		["stagecoach004_2x"] = {"Armored 2-Horse Stagecoach", 0, 6000, 300,0,{"stagecoach","government"}},
		["stagecoach004x"] = {"Armored 4-Horse Stagecoach", 0, 8000, 500,0,{"stagecoach","government"}},
	},	
	{
		name = "SpecialtyWagons",
		["wagonwork01x"] = {"Baker Wagon", 0, 3000, 120,0,{"cook","government"}},
		["cart05"] = {"Barrel Cart", 0, 1500, 30,0,{"nojob"}},
		["wagonCircus02x"] = {"Circus Wagon", 0, 7500, 30,0,{"government"}},
		-- ["wagonCircus01x"] = {"Circus Wagon 2", 0, 4000, 80,0,{"horsetrainer","government"}},		
		["coal_wagon"] = {"Coal Wagon", 0, 3000, 120,0,{"miner","government"}},
		["wagondairy01x"] = {"Dairy Wagon", 0, 3000, 120,0,{"farmer","government"}},
		["wagondoc01x"] = {"Doctor Wagon", 0, 3000, 120,0,{"doctor","government"}},
		-- ["logwagon"] = {"Log Wagon", 0, 3000, 30,0,{"horsetrainer","government"}},
		["oilWagon01x"] = {"Oil Wagon", 0, 2500, 30,0,{"government"}},
		-- ["oilWagon02x"] = {"Oil Wagon 2", 0, 5000, 30,0,{"horsetrainer","government"}},
		["huntercart01"] = {"Hunting Cart", 0, 5000, 80,0,{"nojob"}},
		["wagontraveller01x"] = {"Traveller Wagon", 0, 4500, 120,0,{"nojob"}},
		["utilliwag"] = {"Utility Wagon", 0, 3500, 80,0,{"nojob"}},
	},
	{
		name = "Wagons",
		["wagon03x"] = {"Passenger Wagon", 0, 3500, 30,0,{"nojob"}},
		["chuckwagon000x"] = {"Large Chuck Wagon 1", 0, 5000, 120,0,{"nojob"}},
		["chuckwagon002x"] = {"Large Chuck Wagon 2", 0, 5000, 120,0,{"nojob"}},
		["wagon02x"] = {"Small Chuck Wagon 1", 0, 3500, 80,0,{"nojob"}},
		["wagon04x"] = {"Small Chuck Wagon 2", 0, 3500, 80,0,{"nojob"}},
		["wagon05x"] = {"Small Supply Wagon", 0, 5000, 120,0,{"nojob"}}, 
		["supplywagon"] = {"Large Supply Wagon", 0, 7000, 300,0,{"horsetrainer","farmer","government"}},
	},
}

Config.Horses = { -- please set all the prices to match your server eco correctly
		-- 4th slot is supporter level. has to match db characters 0 is the default is available for everyone
		--5th slot is job lock has to match the player job to be displayed. if player switches jobs while server is live they need to relog for the selection to reset
		-- 5th slot can be {"nojob"} to keep it open for everyone to buy

	{
		name = "American Paint", -- 3rd slot is the new slot. its important that you add it ! its the inventory max for the horse 
		["A_C_Horse_AmericanPaint_Greyovero"] = {"Grey", 0, 200,30,0,{"horsetrainer","government"}}, -- first slot is gold 2nd slot is cash. 
		["A_C_Horse_AmericanPaint_Overo"] = {"Overo", 0, 400, 30,0,{"nojob"}},
		["A_C_Horse_AmericanPaint_SplashedWhite"] = {"Splashwhite", 0, 400, 30,0,{"nojob"}},
		["A_C_Horse_AmericanPaint_Tobiano"] = {"Tobiano", 0, 400, 30,0,{"nojob"}},
	},
	{
		name = "American Standardbred",
		["A_C_Horse_AmericanStandardbred_Black"] = {"Black", 0, 320, 30,0,{"nojob"}},
		["A_C_Horse_AmericanStandardbred_Buckskin"] = {"Buckskin", 0, 420, 30,0,{"nojob"}},
		["A_C_Horse_AmericanStandardbred_PalominoDapple"] = {"PalominoDapple", 0, 420, 30,0,{"nojob"}},
		["A_C_Horse_AmericanStandardbred_SilverTailBuckskin"] = {"SilverTailBuckskin", 0, 420, 30,0,{"nojob"}},
	},
	{
		name = "Andalusian",
		["A_C_Horse_Andalusian_DarkBay"] = {"DarkBay", 0, 420, 30,0,{{"horsetrainer","government"}}},
		["A_C_Horse_Andalusian_Perlino"] = {"Perlino", 0, 420, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Andalusian_RoseGray"] = {"RoseGrey", 0, 420, 30,0,{"horsetrainer","government"}},    
	},
	{
		name = "Appaloosa",
		["A_C_Horse_Appaloosa_BlackSnowflake"] = {"BlackSnowflake", 0, 525, 30,0,{"nojob"}},
		["A_C_Horse_Appaloosa_Blanket"] = {"Blanket", 0, 525, 30,0,{"nojob"}},
		["A_C_Horse_Appaloosa_BrownLeopard"] = {"BrownLeopard", 0, 300, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Appaloosa_FewSpotted_PC"] = {"FewSpots", 0, 525, 30,0,{"nojob"}},
		["A_C_Horse_Appaloosa_Leopard"] = {"Leopard", 0, 300, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Appaloosa_LeopardBlanket"] = {"LeopardBlanket", 0, 525, 30,0,{"nojob"}},
	},
	{
		name = "Arabian",
		["A_C_Horse_Arabian_Black"] = {"BlackHorse", 0, 3000, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Arabian_Grey"] = {"GreyHorse", 0, 3000, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Arabian_RedChestnut"] = {"RedChestnut", 0, 3000, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Arabian_RoseGreyBay"] = {"RoseGreyBay", 0, 3000, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Arabian_WarpedBrindle_PC"] = {"WarpedBrindle", 0, 3000, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Arabian_White"] = {"White", 0, 3000, 30,0,{"horsetrainer","government"}},
	
	},
	{
		name = "Ardennes",
		["A_C_Horse_Ardennes_BayRoan"] = {"BayRoan", 0, 300, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Ardennes_IronGreyRoan"] = {"IronGreyRoan", 0, 300, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Ardennes_StrawberryRoan"] = {"StrawberryRoan", 0, 300, 30,0,{"horsetrainer","government"}},
	},
	{
		name = "Belgian",
		["A_C_Horse_Belgian_BlondChestnut"] = {"BlondChestnut", 0, 300, 30,0,{"nojob"}},
		["A_C_Horse_Belgian_MealyChestnut"] = {"MealyChestnut", 0, 300, 30,0,{"nojob"}},
	},
	{
		name = "Dutch Warmblood",
		["A_C_Horse_DutchWarmblood_ChocolateRoan"] = {"ChocolateRoan", 0, 300, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_DutchWarmblood_SealBrown"] = {"SealBrown", 0, 450, 30,0,{"nojob"}},
		["A_C_Horse_DutchWarmblood_SootyBuckskin"] = {"SootyBuckskin", 0, 450, 30,0,{"nojob"}},
	},
	{
		name = "Gypsy Cob",
		["a_c_horse_gypsycob_palominoblagdon"] = {"PalominoBlagdon", 0, 1500, 30,0,{"horsetrainer","government"}},
		["a_c_horse_gypsycob_piebald"] = {"Piebald", 0, 1500, 30,0,{"horsetrainer","government"}},
		["a_c_horse_gypsycob_splashedbay"] = {"SplashedBay", 0, 1500, 30,0,{"horsetrainer","government"}},
		["a_c_horse_gypsycob_splashedpiebald"] = {"SplashedPiebald", 0, 1500, 30,0,{"horsetrainer","government"}},
		["a_c_horse_gypsycob_skewbald"] = {"Skewbald", 0, 1500, 30,0,{"horsetrainer","government"}},
		["a_c_horse_gypsycob_whiteblagdon"] = {"WhiteBlagdon", 0, 1500, 30,0,{"horsetrainer","government"}},	
	},
	{
		name = "Hungarian Halfbred",
		["A_C_Horse_HungarianHalfbred_DarkDappleGrey"] = {"DarkDappleGrey", 0, 460, 30,0,{"nojob"}},
		["A_C_Horse_HungarianHalfbred_FlaxenChestnut"] = {"FlaxenChestnut", 0, 460, 30,0,{"nojob"}},
		["A_C_Horse_HungarianHalfbred_LiverChestnut"] = {"LiverChestnut", 0, 460, 30,0,{"nojob"}},
		["A_C_Horse_HungarianHalfbred_PiebaldTobiano"] = {"PiebaldTobiano", 0, 460, 30,0,{"nojob"}},
	},
	{
		name = "Kentucky Saddle",
		["A_C_Horse_KentuckySaddle_Black"] = {"BlackSaddler", 0, 180, 30,0,{"nojob"}},
		["A_C_Horse_KentuckySaddle_ButterMilkBuckskin_PC"] = {"ButterMilkBuckskin", 0, 180, 30,0,{"nojob"}},
		["A_C_Horse_KentuckySaddle_ChestnutPinto"] = {"ChestnutPinto", 0, 180, 30,0,{"nojob"}},
		["A_C_Horse_KentuckySaddle_Grey"] = {"GreySaddler", 0, 180, 30,0,{"nojob"}},
		["A_C_Horse_KentuckySaddle_SilverBay"] = {"SilverBay", 0, 180, 30,0,{"nojob"}},
	},
	{
		name = "Kladruber",
		["A_C_Horse_Kladruber_Black"] = {"BlackKladruber", 0, 440, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Kladruber_Silver"] = {"Silver", 0, 440, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Kladruber_Cremello"] = {"Cremello", 0, 440, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Kladruber_Grey"] = {"GreyKladruber", 0, 440, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Kladruber_DappleRoseGrey"] = {"DappleRoseGrey", 0, 440, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Kladruber_White"] = {"WhiteKladruber", 0, 440, 30,0,{"horsetrainer","government"}},
	},
	{
		name = "Missouri Fox Trotter",
		["A_C_Horse_MissouriFoxTrotter_AmberChampagne"] = {"AmberChampagne", 0, 440, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_MissouriFoxTrotter_SableChampagne"] = {"SableChampagne", 0, 440, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_MissouriFoxTrotter_SilverDapplePinto"] = {"SilverDapplePinto", 0, 440, 30,0,{"horsetrainer","government"}},
        ["a_c_horse_missourifoxtrotter_blacktovero"] = {"BlackTrovero", 0, 440, 30,0,{"horsetrainer","government"}},   
        ["a_c_horse_missourifoxtrotter_blueroan"] = {"Blue", 0, 440, 30,0,{"horsetrainer","government"}},   
        ["a_c_horse_missourifoxtrotter_buckskinbrindle"] = {"BuckskinBrindle", 0, 440, 30,0,{"horsetrainer","government"}},  
        ["a_c_horse_missourifoxtrotter_dapplegrey"] = {"DappleGrey", 0, 440, 30,0,{"horsetrainer","government"}},
	},
	{
		name = "Morgan",
		["A_C_Horse_Morgan_Bay"] = {"Bay", 0, 80, 30,0,{"nojob"}},
		["A_C_Horse_Morgan_BayRoan"] = {"BayRoanH", 0, 80, 30,0,{"nojob"}},
		["A_C_Horse_Morgan_FlaxenChestnut"] = {"Flaxen", 0, 80, 30,0,{"nojob"}},
		["A_C_Horse_Morgan_LiverChestnut_PC"] = {"Liver", 0, 80, 30,0,{"nojob"}},
		["A_C_Horse_Morgan_Palomino"] = {"Palomino", 0, 80, 30,0,{"nojob"}},
	},
	{
		name = "Mustang",
		["A_C_Horse_Mustang_GoldenDun"] = {"GoldenDun", 0, 2000, 30,0,{"nojob"}},
		["A_C_Horse_Mustang_GrulloDun"] = {"GrulloDun", 0, 2000, 30,0,{"nojob"}},
		["A_C_Horse_Mustang_TigerStripedBay"] = {"TigerStripedBay", 0, 2000, 30,0,{"nojob"}},
		["A_C_Horse_Mustang_WildBay"] = {"WildBay", 0, 2000, 30,0,{"nojob"}},
		["a_c_horse_mustang_blackovero"] = {"BlackOvero", 0, 1500, 30,0,{"horsetrainer","government"}},    
        ["a_c_horse_mustang_buckskin"] = {"BuckSkinn", 0, 1500, 30,0,{"horsetrainer","government"}},  
        ["a_c_horse_mustang_chestnuttovero"] = {"ChestnutTovero", 0, 1500, 30,0,{"horsetrainer","government"}}, 
        ["a_c_horse_mustang_reddunovero"] = {"RedDunOvero", 0, 1500, 30,0,{"horsetrainer","government"}},   
	},
	{
		name = "Nokota",
		["A_C_Horse_Nokota_BlueRoan"] = {"BlueRoan", 0, 460, 30,0,{"nojob"}},
		["A_C_Horse_Nokota_ReverseDappleRoan"] = {"ReverseDappleRoan", 0, 460, 30,0,{"nojob"}},
		["A_C_Horse_Nokota_WhiteRoan"] = {"WhiteRoan", 0, 460, 30,0,{"nojob"}},
	},
	{
		name = "Shire",
		["A_C_Horse_Shire_DarkBay"] = {"Dark", 0, 330, 30,0,{"nojob"}},
		["A_C_Horse_Shire_LightGrey"] = {"LightGrey", 0, 330, 30,0,{"nojob"}},
		["A_C_Horse_Shire_RavenBlack"] = {"RavenBlack", 0, 330, 30,0,{"nojob"}},
	},
	{
		name = "Suffolk Punch",
		["A_C_Horse_SuffolkPunch_RedChestnut"] = {"Red", 0, 290, 30,0,{"nojob"}},
		["A_C_Horse_SuffolkPunch_Sorrel"] = {"Sorrel", 0, 290, 30,0,{"nojob"}},
	},
	{
		name = "Tennessee Walker",
		["A_C_Horse_TennesseeWalker_BlackRabicano"] = {"BlackRabicano", 0, 100, 30,0,{"nojob"}},
		["A_C_Horse_TennesseeWalker_Chestnut"] = {"Chestnut", 0, 100, 30,0,{"nojob"}},
		["A_C_Horse_TennesseeWalker_DappleBay"] = {"DappleBay", 0, 100, 30,0,{"nojob"}},
		["A_C_Horse_TennesseeWalker_FlaxenRoan"] = {"FlaxenRoan", 0, 100, 30,0,{"nojob"}},
		["A_C_Horse_TennesseeWalker_MahoganyBay"] = {"MahoganyBay", 0, 100, 30,0,{"nojob"}},
		["A_C_Horse_TennesseeWalker_RedRoan"] = {"RedRoan", 0, 100, 30,0,{"nojob"}},
		["A_C_Horse_TennesseeWalker_GoldPalomino_PC"] = {"GoldPalomino", 0, 100, 30,0,{"nojob"}},
	},
	{
		name = "Thoroughbred",
		["A_C_Horse_Thoroughbred_BlackChestnut"] = {"BlackChestnut", 0, 1400, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Thoroughbred_BloodBay"] = {"BloodBay", 0, 1400, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Thoroughbred_Brindle"] = {"Brindle", 0, 1400, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Thoroughbred_DappleGrey"] = {"Dapple", 0, 1400, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Thoroughbred_ReverseDappleBlack"] = {"DappleBlack", 0, 1400, 30,0,{"horsetrainer","government"}},
	},
	{
		name = "Turkoman",
		["A_C_Horse_Turkoman_DarkBay"] = {"DarkTurko", 0, 2000, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Turkoman_Gold"] = {"GoldTurko", 0, 2000, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Turkoman_Silver"] = {"SilverTurko", 0, 2000, 30,0,{"horsetrainer","government"}},
		["a_c_horse_turkoman_black"] = {"BlackTurko", 0, 2000, 30,0,{"horsetrainer","government"}},   
        ["a_c_horse_turkoman_chestnut"] = {"ChestnutTurko", 0, 2000, 30,0,{"horsetrainer","government"}},
		["a_c_horse_turkoman_grey"] = {"GreyTurko", 0, 2000, 30,0,{"horsetrainer","government"}},    
        ["a_c_horse_turkoman_perlino"] = {"PerlinoTurko", 0, 2000, 30,0,{"horsetrainer","government"}},
	},
	{
		name = "Criollo",
		["A_C_Horse_Criollo_Dun"] = {"Dun", 0, 650, 30,0,{"nojob"}},
		["A_C_Horse_Criollo_MarbleSabino"] = {"MarbleSabino", 0, 270, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Criollo_BayFrameOvero"] = {"BayFrameOvero", 0, 270, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Criollo_BayBrindle"] = {"BayBrindle", 0, 650, 30,0,{"nojob"}},
		["A_C_Horse_Criollo_SorrelOvero"] = {"SorrelOvero", 0, 650, 30,0,{"nojob"}},
		["A_C_Horse_Criollo_BlueRoanOvero"] = {"BlueRoanOvero", 0, 650, 30,0,{"nojob"}},
	},
	{
		name = "Breton",
		["A_C_Horse_Breton_SteelGrey"] = {"SteelGrey", 0, 560, 30,0,{"horsetrainer","government"}},
		["a_c_horse_breton_mealydapplebay"] = {"MealyDapple", 0, 560, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Breton_SealBrown"] = {"Seal", 0, 560, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Breton_GrulloDun"] = {"GrulloDun", 0, 560, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Breton_Sorrel"] = {"SorrelBreton", 0, 560, 30,0,{"horsetrainer","government"}},
		["A_C_Horse_Breton_RedRoan"] = {"Roan Red", 0, 560, 30,0,{"horsetrainer","government"}},
	},
	{
		name = "Norfolk Roadster",
		["A_C_HORSE_NORFOLKROADSTER_BLACK"] = {"BlackNor", 0, 800, 30,0,{"nojob"}},
		["A_C_HORSE_NORFOLKROADSTER_SPECKLEDGREY"] = {"SpeckLedGrey", 0, 800, 30,0,{"nojob"}},
		["A_C_HORSE_NORFOLKROADSTER_PIEBALDROAN"] = {"PiebaldRoan", 0, 800, 30,0,{"nojob"}},
		["A_C_HORSE_NORFOLKROADSTER_ROSEGREY"] = {"Grey Rose", 0, 450, 30,0,{"horsetrainer","government"}},
		["A_C_HORSE_NORFOLKROADSTER_DAPPLEDBUCKSKIN"] = {"DappleBuck", 0, 450, 30,0,{"horsetrainer","government"}},
		["A_C_HORSE_NORFOLKROADSTER_SPOTTEDTRICOLOR"] = {"SpottedTri", 0, 450, 30,0,{"horsetrainer","government"}},
	},
	{
		name = "Nags",
		["A_C_Horse_MP_Mangy_Backup"] = {"Mangy", 0, 30, 30,0,{"nojob"}},
		["a_c_horse_murfreebrood_mange_01"] = {"Murfreebrood Mange 1", 0, 10, 30,0,{"nojob"}},
		["a_c_horse_murfreebrood_mange_02"] = {"Murfreebrood Mange 2", 0, 10, 30,0,{"nojob"}},
		["a_c_horse_murfreebrood_mange_03"] = {"Murfreebrood Mange 3", 0, 10, 30,0,{"nojob"}},
		["A_C_HorseMule_01"] = {"Mule", 0, 1500, 30,0,{"nojob"}},
		["A_C_Donkey_01"] = {"Donkey", 0, 1000, 30,0,{"nojob"}},
	},
	{
		name = "Rare",
		["A_C_HorseMulePainted_01"] = {"Zebra", 0, 10000, 30,0,{"showman","horsetrainer","government"}},
		["p_c_horse_01"] = {"Horse", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_americanstandardbred_lightbuckskin"] = {"Standardbred Light Buckskin", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_arabian_redchestnut_pc"] = {"Special Red Arabian", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_buell_warvets"] = {"Buell Warvets", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_eagleflies"] = {"Eagleflies", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_bill"] = {"Bills", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_charles"] = {"Charles", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_charles_endlesssummer"] = {"Charles 2", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_dutch"] = {"Dutch", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_hosea"] = {"Hosea", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_javier"] = {"Javier", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_john"] = {"John", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_karen"] = {"Karen", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_kieran"] = {"Kieran", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_lenny"] = {"Lenny", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_micah"] = {"Micha", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_sadie"] = {"Sadie", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_sadie_endlesssummer"] = {"Sadie 2", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_sean"] = {"Sean", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_trelawney"] = {"Trelawney", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_uncle"] = {"Uncle", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_gang_uncle_endlesssummer"] = {"Uncle 2", 0, 1000, 30,5,{"horsetrainer","government"}},
		["a_c_horse_john_endlesssummer"] = {"John 2", 0, 1000, 30,5,{"horsetrainer","government"}},
		-- ["a_c_horse_winter02_01"] = {"Winter", 0, 1000, 30,5,{"horsetrainer","government"}},
	},
}

Config.Language = { -- space is very important edit your language here ! 
	["qt"] = "Invalid quantity",
	["horsemax"] = "Your horse cannot carry more items, saddle limit is ",	
	["wagonmax"] = "Your wagon cannot store more items, inventory limit is ",	
	["carry"] = "You cannot carry more items",
    ["limit"] = "You reached the limit for this item",
    ["givehorse"] = "You gave your horse to ",
    ["givewagon"] = "You gave your wagon to ",
    ["receiveHorse"] = "You received a horse ownership deed from ",
    ["receivewagon"] = "You received a wagon ownership deed from ",
    ["horselimit"] = "You have too many horses already",
    ["wagonlimit"] = "You have too many wagons already",
    ["horselimit2"] = " is at stable slot limit",
    ["wagonlimit2"] = " is at stable slot limit",
	["wrongid"] = "Wrong ID",
	["nogold"] = "Not Enough Gold",
	["nocash"] = "Not Enough Cash",
	["limitwagon"] = "You cannot buy any more wagons",
	["limithorse"] = "You cannot buy any more horses",
	["horsesold"] = "You have sold your horse",
	["wagonsold"] = "You have sold your wagon",
	["open"] = "Open Stable",
	["stable"] = "Stable",
	["name"] = "Name your horse:",
	["name2"] = "Name your wagon:",
	["nowagon"] = "You do not have a wagon selected",
	["nohorse"] = "You do not have a horse selected",
	["horseinfo"] = "Horse Info:",
	["wagoninfo"] = "Wagon Info:",
	["sure"] = "Are you sure?",
	["horsename"] = "Horse Name: ",
	["horsetrainlevel"] = "Horse Training Level: ",
	["horsetrainexp"] = "Horse Training Exp: ",
	["givehorseowner"] = "Transfer Horse Ownership",
	["saddlebags"] = "Saddle Bags",
	["wagonname"] = "Wagon Name: ",
	["dismiss"] = "Dismiss Wagon",
	["givewagonowner"] = "Transfer Wagon Ownership",
	["wagoninv"] = "Inventory",
	["yes"] = "YES",
	["no"] = "NO",
	["wagon"] = "Wagon",
	["tired"] = "You are too tired to train your horse",
	["tired2"] = "You both need some rest - training stopped for 5 minutes",
	["better"] = "You feel better and can train your horse",
	["level2"] = "You need to increase your bond with your horse",
	["level3"] = "You need to increase your bond with your horse",
	["level4"] = "You need to increase your bond with your horse",
	["water"] = "Your horse is not in water",
	["deadhorse"] = "Your horse is injured - please try again shortly", 
	["payfordead"] = "Your horse has been healed by the vet. You paid ",
	["equipment"] = "Outfitter Menu",
	["sex"] = "Horse Sex",
	["cancel"] = "Cancel Buying",
	["male"] = "Male",
	["female"] = "Female",
	["toofarfromstable"] = "Too far from stable",
	["someonesearch"] = "Someone is searching already", 
	["tooclosetown"] = "Too close to town",
	["waypoint"] = "Waypoint", -- new line
	["processing"] = "Please Wait",
}

