Config = {}
Config.keys = {
    ["G"] = 0x760A9C6F,
    ["F"] = 0xB2F377E8,
	["BACKSPACE"] = 0x156F7119,
    ["ENTER"] = 0xC7B5340A,

}


Config.blacklisteditems = {
    "acid",
    "Agarita",
    "Agarita_Seed",
    "Alaskan_Ginseng",
    "Alaskan_Ginseng_Seed",
    -- "alcohol",
    "American_Ginseng",
    "American_Ginseng_Seed",
    "ammoarrmownormal",
    "ammoarrowdynamite",
    "ammoarrowfire",
    "ammoarrowimproved",
    "ammoarrowpoison",
    "ammoarrowsmallgame",
    "ammobolahawk",
    "ammobolainterwired",
    "ammobolaironspiked",
    "ammobolla",
    "ammodynamite",
    "ammoelephant",
    "ammoknives",
    "ammomolotov",
    "ammopistolexplosive",
    "ammopistolexpress",
    "ammopistolnormal",
    "ammopistolsplitpoint",
    "ammopistolvelocity",
    "ammopoisonbottle",
    "ammorepeaterexplosive",
    "ammorepeaterexpress",
    "ammorepeaternormal",
    "ammorepeatersplitpoint",
    "ammorepeatervelocity",
    "ammorevolverexplosive",
    "ammorevolverexpress",
    "ammorevolvernormal",
    "ammorevolversplitpoint",
    "ammorevolvervelocity",
    "ammorifleexplosive",
    "ammorifleexpress",
    "ammoriflenormal",
    "ammoriflesplitpoint",
    "ammoriflevelocity",
    "ammoshotgunexplosive",
    "ammoshotgunincendiary",
    "ammoshotgunnormal",
    "ammoshotgunslug",
    "ammotomahawk",
    "ammovarmint",
    "ammovarminttranq",
    "ammovoldynamite",
    "ammovolmolotov",
    "antipoison",
    -- "apple",
    "appleBerryMash",
    "appleBerryMoonshine",
    "appleCrumbMash",
    "appleCrumbMoonshine",
    -- "apple_pie",
    -- "a_c_fishbluegil_01_ms",
    -- "a_c_fishbluegil_01_sm",
    -- "a_c_fishbullheadcat_01_ms",
    -- "a_c_fishbullheadcat_01_sm",
    -- "a_c_fishchainpickerel_01_ms",
    -- "a_c_fishchainpickerel_01_sm",
    -- "a_c_fishlargemouthbass_01_ms",
    -- "a_c_fishperch_01_ms",
    -- "a_c_fishperch_01_sm",
    -- "a_c_fishrainbowtrout_01_ms",
    -- "a_c_fishredfinpickerel_01_ms",
    -- "a_c_fishredfinpickerel_01_sm",
    -- "a_c_fishrockbass_01_ms",
    -- "a_c_fishrockbass_01_sm",
    -- "a_c_fishsalmonsockeye_01_ms",
    -- "a_c_fishsmallmouthbass_01_ms",
    "bait",
    -- "banana",
    -- "bananaCreamPie",
    -- "bandage",
    "basket",
    "Bay_Bolete",
    "Bay_Bolete_Seed",
    "beefjerky",
    -- "beer",
    "Big_Leather",
    "binoculars",
    "Bitter_Weed",
    "Bitter_Weed_Seed",
    "blackberryale",
    -- "Black_Berry",
    -- "Black_Berry_Seed",
    -- "Black_Currant",
    -- "Black_Currant_Seed",
    "Blood_Flower",
    "Blood_Flower_Seed",
    -- "blueberry",
    -- "blueberrypie",
    "boiledegg",
    "bone",
    -- "book",
    "bountylicns",
    -- "boxedchocs",
    -- "bread",
    "Bulrush",
    "Bulrush_Seed",
    "Burdock_Root",
    "Burdock_Root_Seed",
    -- "cake",
    -- "camera",
    -- "campfire",
    -- "campfire_stew",
    -- "candyapple",
    "capitale",
    "Cardinal_Flower",
    "Cardinal_Flower_Seed",
    -- "carrots",
    -- "chalkboard",
    "Chanterelles",
    "Chanterelles_Seed",
    "char",
    -- "charcoal",
    "chestnut",
    -- "chewingtobacco",
    -- "chocstrawberry",
    "Choc_Daisy",
    "Choc_Daisy_Seed",
    -- "cigar",
    "cigarcheapbox",
    -- "cigarette",
    "cigarettecheapbox",
    "cigarettefilter",
    "cigarettepremiumbox",
    "cigarpremiumbox",
    -- "clay",
    -- "cloth",
    -- "coal",
    -- "cocoa",
    -- "coffee",
    -- "consumable_biscuits",
    "consumable_bluegil",
    "consumable_breakfast",
    -- "consumable_caramel",
    -- "consumable_chocolate",
    -- "consumable_cocoa",
    -- "consumable_coffee",
    -- "consumable_eggnog",
    "consumable_fruitsalad",
    -- "consumable_game",
    -- "consumable_haycube",
    -- "consumable_herb_chanterelles",
    -- "consumable_herb_evergreen_huckleberry",
    -- "consumable_herb_oregano",
    -- "consumable_herb_vanilla_flower",
    -- "consumable_herb_wintergreen_berry",
    -- "consumable_kidneybeans_can",
    "consumable_lock_breaker",
    "consumable_meat_greavy",
    -- "consumable_medicine",
    -- "consumable_oatcakes",
    -- "consumable_peach",
    -- "consumable_pear",
    "consumable_raspberrywater",
    "consumable_salmon",
    -- "consumable_salmon_can",
    -- "consumable_snake_oil",
    "consumable_trout",
    "consumable_veggies",
    "cookedbluegil",
    -- "copper",
    -- "copperbar",
    -- "coppertube",
    -- "corn",
    -- "cornbread",
    -- "corned_beef",
    -- "corned_beef_hash",
    -- "cornseed",
    "Creeking_Thyme",
    "Creeking_Thyme_Seed",
    "Creekplum",
    "Creekplum_Seed",
    "Crows_Garlic",
    "Crows_Garlic_Seed",
    -- "dandybouquet",
    -- "dandyflwr",
    "Desert_Sage",
    "Desert_Sage_Seed",
    -- "diamond",
    "Drink_For_Dog",
    "Duck_Egg",
    "dynamite",
    -- "eggs",
    -- "elegantnecklace",
    -- "emerald",
    "emeraldearrings",
    "English_Mace",
    "English_Mace_Seed",
    "Evergreen_Huckleberry",
    -- "Evergreen_Huckleberry_Seed",
    -- "fan",
    "Fat",
    "feather",
    "Feed_For_Dog",
    -- "fibers",
    "fish",
    "fishbait",
    "fishchips",
    "flag",
    -- "flossandwich",
    -- "flour",
    "friedtater",
    "Gamey_Meat",
    "Gator_Egg_3",
    "Gator_Egg_4",
    "Gator_Egg_5",
    -- "gelatin",
    -- "gingerbread",
    "ginsengtea",
    -- "glassbottle",
    -- "goldbar",
    -- "goldbracelet",
    -- "goldcrossnecklace",
    "Golden_Currant",
    "Golden_Currant_Seed",
    "goldfish",
    -- "goldlocket",
    -- "goldnugget",
    -- "goldpan",
    -- "goldring",
    "goldtooth",
    "Goose_Egg_4",
    -- "gunpowder",
    -- "gun_oil",
    -- "hairpomade",
    "handcuffs",
    "handkerchief",
    -- "hardcandy",
    -- "hatchet",
    "Health_For_Dog",
    "hemp",
    "hemp_cig",
    "herbmed",
    "heroin",
    -- "honey",
    -- "horsebrush",
    "Hummingbird_Sage",
    "Hummingbird_Sage_Seed",
    -- "hush_puppies",
    -- "hwood",
    -- "icedcream",
    "Indian_Tobbaco",
    "Indian_Tobbaco_Seed",
    -- "iron",
    -- "ironbar",
    "ironextract",
    "ironhammer",
    -- "kibble",
    "kit_bandana",
    "leather",
    -- "lettuce",
    "lockpick",
    "lockpickmold",
    -- "lovebracelet",
    -- "lupinbouquet",
    -- "lupinflwr",
    "mackerel",
    -- "marshmallow",
    -- "meat",
    -- "meatpotatopie",
    -- "milk",
    -- "milkweedbouquet",
    -- "milkweedflwr",
    "Milk_Weed",
    "Milk_Weed_Seed",
    -- "moneyclip",
    "moonshine",
    "morpcert",
    "morphine",
    "mp001_p_mp_still02x",
    "Mutton",
    "nailfile",
    -- "nails",
    -- "newspaper",
    "nitrite",
    -- "nitroglycerin",
    "notebook",
    "notepad",
    -- "oatmeal",
    "oldbuckle",
    "oldwatch",
    "Oleander_Sage",
    "Oleander_Sage_Seed",
    -- "onion",
    "opium",
    "Oregano",
    "Oregano_Seed",
    -- "paper",
    -- "parasol",
    "Parasol_Mushroom",
    "Parasol_Mushroom_Seed",
    -- "peach_cobbler",
    -- "peacockfeather",
    -- "pearllocket",
    -- "pearlring",
    -- "peppermint",
    -- "pepsi",
    -- "phonograph",
    -- "pickaxe",
    -- "pipe",
    "piratecoin",
    "pocketknife",
    "pocket_watch",
    -- "polenta",
    -- "poppedcorn",
    -- "poppybouquet",
    -- "poppyflwr",
    -- "pork_n_beans",
    -- "potato",
    "Prairie_Poppy",
    "Prairie_Poppy_Seed",
    -- "premiumchoc",
    -- "pulp",
    "purppetunia",
    -- "p_baitBread01x",
    -- "p_baitCheese01x",
    -- "p_baitCorn01x",
    -- "p_baitCricket01x",
    -- "p_baitWorm01x",
    -- "p_barrelmoonshine",
    -- "p_crawdad01x",
    -- "p_FinisdFishlure01x",
    -- "p_finisdfishlurelegendary01x",
    -- "p_finishdcrawd01x",
    -- "p_finishdcrawdlegendary01x",
    -- "p_finishedragonfly01x",
    -- "p_finishedragonflylegendary01x",
    -- "p_lgoc_spinner_v4",
    -- "p_lgoc_spinner_v6",
    -- "quartz",
    "Rams_Head",
    "Rams_Head_Seed",
    "raspberryale",
    "redpetunia",
    -- "Red_Raspberry",
    -- "Red_Raspberry_Seed",
    "Red_Sage",
    "Red_Sage_Seed",
    "repeaterbarrel",
    "repeatermold",
    "repeaterreceiver",
    "repeaterrecmold",
    "repeaterstock",
    "revolverbarrel",
    "revolvercylinder",
    "revolverhandle",
    "revolvermold",
    "riflebarrel",
    "riflemold",
    "riflereceiver",
    "riflerecmold",
    "riflestock",
    "roach",
    "robbingkit",
    -- "rock",
    -- "rolledoats",
    "rollingpaper",
    -- "rootbeer",
    -- "rope",
    -- "rubber",
    -- "ruby",
    -- "rubyring",
    "salamelle",
    -- "saline",
    "salmon",
    -- "salt",
    "Saltbush",
    "Saltbush_Seed",
    -- "saltpeter",
    -- "sandwich",
    -- "sap",
    -- "sapphire",
    -- "sapphirebracelet",
    -- "sarsaparilla",
    "scale",
    -- "seasoning",
    "secondchance",
    "shellcasing",
    "shotgunbarrel",
    "shotgunmold",
    "shotgunstock",
    "shrimps",
    -- "silver",
    -- "silverbar",
    -- "silverbracelet",
    -- "silverpen",
    -- "silverpocketmirror",
    -- "silverring",
    "sketchbook",
    "Small_Leather",
    -- "smores",
    "SnakeSkin",
    "Snake_Poison",
    "soborno",
    "steak",
    "steakveg",
    -- "stim",
    "stolenmerch",
    "stonehammer",
    -- "strawberry",
    -- "sugar",
    -- "sugarcaneseed",
    -- "sulfur",
    -- "sweetpotato",
    "syn",
    "synpackage",
    "syringe",
    "syringecert",
    "taffy",
    -- "tea",
    "tent",
    "tequila",
    "Texas_Bonnet",
    "Texas_Bonnet_Seed",
    -- "toastedmarshmallow",
    -- "tobacco",
    -- "tobaccoseed",
    "token",
    -- "tomato",
    "trainkey",
    "tropicalPunchMash",
    "tropicalPunchMoonshine",
    "trout",
    "TurtleShell",
    "tylenol",
    "veggie_stew",
    "Violet_Snowdrop",
    "Violet_Snowdrop_Seed",
    "vodka",
    "Volture_Egg",
    "walnut",
    -- "water",
    -- "wateringcan",
    "wateringcan_dirtywater",
    "wateringcan_empty",
    -- "waterskin",
    "weapon_lasso",
    -- "weddingband",
    -- "whisky",
    "wildCiderMash",
    "wildCiderMoonshine",
    -- "wildflowerbouquet",
    "Wild_Carrot_Seed",
    "Wild_Feverfew",
    "Wild_Feverfew_Seed",
    -- "Wild_Mint",
    "Wild_Mint_Seed",
    -- "Wild_Rhubarb",
    -- "Wild_Rhubarb_Seed",
    "wine",
    "Wintergreen_Berry",
    -- "Wintergreen_Berry_Seed",
    "Wisteria",
    "Wisteria_Seed",
    "wojape",
    -- "wood",
    "woodencrate",
    -- "wooden_boards",
    "wool",
    "Yarrow",
    "Yarrow_Seed",
    -- "yeast",
    -- "zinc",
}

Config.marketplace = {  
    ["Valentine"] = {	   
        Pos = {x=-179.35, y=648.28, z=113.58},
        blipsprite = 249721687, 
        name = 'Valentine Market Place', 
        showblip = true,
    },
    ["Rhodes"] = {	   
        Pos = {x = 1231.26, y = -1278.16, z = 76.0},
        blipsprite = 249721687, 
        name = 'Rhodes Market Place', 
        showblip = true,
    },
    ["SD"] = {	   
        Pos = {x = 2753.69, y = -1395.44, z = 46.19},
        blipsprite = 249721687, 
        name = 'Saint Denis Market Place', 
        showblip = true,
    },
    ["blackwater"] = {	   
        Pos = {x=-877.87, y=-1343.73, z=43.29},
        blipsprite = 249721687, 
        name = 'Blackwater Market Place', 
        showblip = true,
    },
    ["Strawberry"] = {	   
        Pos = {x = -1752.16, y = -387.04, z = 156.48},
        blipsprite = 249721687, 
        name = 'Strawberry Market Place', 
        showblip = true,
    },
    ["Armadillo"] = {	   
        Pos = {x = -3729.29, y = -2616.42, z = -13.3},
        blipsprite = 249721687, 
        name = 'Armadillo Market Place', 
        showblip = true,
    },
    ["Annesburg"] = {	   
        Pos = {x = 2932.64, y = 1302.13, z = 44.46},
        blipsprite = 249721687, 
        name = 'Annesburg Market Place', 
        showblip = true,
    },
}

Config.invpath = "nui://vorp_inventory/html/img/items/" -- this is the inventory path for vorp, change it to your redem one if ur using redem
Config.minimumpriceperitem = 0.05 -- min price per item 
Config.liccost = 100 -- cost to buy listing license
Config.initalinventoryspace = 100 -- inital inventory space for listing, set to 0 for unlimited
Config.upgradeslots = true -- allow players to upgrade slots, if u set above to 0 set this to false
Config.priceperslot = 10 -- cost per slot
Config.webhook = ""
Config.webhookavatar = "https://media.discordapp.net/attachments/805495169901789194/911352236725129226/unknown.png"
Config.webhookicon = "https://media.discordapp.net/attachments/805495169901789194/921620092704423986/SYN5.png"
Config.language = {
    openmenu = "Open Menu",
    marketplace = " Market Place",
    marketmenu = " Market Menu",
    buylicense    = " Buy Listing License",
    buylicensedesc   = " Buy a listing license",
    nomoney = "Not Enough Money $ ",
    purchasedlic = "License Purchased Successfully",
    buyslots = "$10 per slot",
    slots = "Buy Extra Slots",
    slots2 = "Slots: ",
    boughtslots = "You Purchased Extra Slots, ",
    requestitems = "Request Items",
    search = "Search",
    amount = "amount",
    amountdesc = "Amount of the item to purchase: ",
    price = "Payment",
    pricedesc = "money to pay for the total amount: $",
    confirm = "Confirm",
    confirmdesc = "confirm order",
    slots3 = "slots",
    name = "item name",
    ordersucc = "order successful",
    removelist = "Remove Listing",
    listingupdated = "Listing Updated",
    viewlisting = "View Market Listing",
    priceper = "Price Per Item",
    amountx = " / Amount:",
    slotsx = " / Slots:",
    dollar = ": $",
    maxslots = "Not Enough Space in listers inventory, slot limit is ",	
    invalidamount = "Invalid Amount",
    openinv = "Open Inventory",
    slotsy = "Slots: ",
    materialorder = "Material Order",
    posted = " posted",
    mro = "material Request of ",
    pricetoolow = "price per item is too low. item will be removed from listing and money refunded. minimum price per item : ",
    pricetoolow2 = "price per item is too low. minimum price per item : ",
    paid = "paid $",
}